//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Serezhatatarincev2
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Действие.
    /// </summary>
    // *** Start programmer edit section *** (Действие CustomAttributes)

    // *** End programmer edit section *** (Действие CustomAttributes)
    public enum Действие
    {
        
        // *** Start programmer edit section *** (Действие.Установка CustomAttributes)

        // *** End programmer edit section *** (Действие.Установка CustomAttributes)
        [Caption("Установка")]
        Установка,
        
        // *** Start programmer edit section *** (Действие.Изменение CustomAttributes)

        // *** End programmer edit section *** (Действие.Изменение CustomAttributes)
        [Caption("Изменение")]
        Изменение,
    }
}
