//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Serezhatatarincev2
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Оборудование.
    /// </summary>
    // *** Start programmer edit section *** (Оборудование CustomAttributes)

    // *** End programmer edit section *** (Оборудование CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ОборудованиеE", new string[] {
            "Название as \'Название\'",
            "ИнвНомер as \'Инв номер\'",
            "Дата as \'Дата добавления\'",
            "Тип as \'Тип\'",
            "Тип.Название as \'Название\'",
            "Операции as \'Операции\'",
            "Операции.Дата as \'Дата \'",
            "Пользователь as \'Пользователь\'",
            "Пользователь.ФИО as \'ФИО\'"}, Hidden=new string[] {
            "Тип.Название",
            "Операции.Дата",
            "Пользователь.ФИО"})]
    [MasterViewDefineAttribute("ОборудованиеE", "Тип", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Название")]
    [MasterViewDefineAttribute("ОборудованиеE", "Операции", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Дата")]
    [MasterViewDefineAttribute("ОборудованиеE", "Пользователь", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИО")]
    public class Оборудование : ICSSoft.STORMNET.DataObject
    {
        
        private string fНазвание;
        
        private string fИнвНомер;
        
        private System.DateTime fДата;
        
        private IIS.Serezhatatarincev2.Тип fТип;
        
        private IIS.Serezhatatarincev2.Операции fОперации;
        
        private IIS.Serezhatatarincev2.Пользователь fПользователь;
        
        private IIS.Serezhatatarincev2.РабочееМесто fРабочееМесто;
        
        // *** Start programmer edit section *** (Оборудование CustomMembers)

        // *** End programmer edit section *** (Оборудование CustomMembers)

        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (Оборудование.Дата CustomAttributes)

        // *** End programmer edit section *** (Оборудование.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (Оборудование.Дата Get start)

                // *** End programmer edit section *** (Оборудование.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (Оборудование.Дата Get end)

                // *** End programmer edit section *** (Оборудование.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Оборудование.Дата Set start)

                // *** End programmer edit section *** (Оборудование.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (Оборудование.Дата Set end)

                // *** End programmer edit section *** (Оборудование.Дата Set end)
            }
        }
        
        /// <summary>
        /// ИнвНомер.
        /// </summary>
        // *** Start programmer edit section *** (Оборудование.ИнвНомер CustomAttributes)

        // *** End programmer edit section *** (Оборудование.ИнвНомер CustomAttributes)
        [StrLen(255)]
        public virtual string ИнвНомер
        {
            get
            {
                // *** Start programmer edit section *** (Оборудование.ИнвНомер Get start)

                // *** End programmer edit section *** (Оборудование.ИнвНомер Get start)
                string result = this.fИнвНомер;
                // *** Start programmer edit section *** (Оборудование.ИнвНомер Get end)

                // *** End programmer edit section *** (Оборудование.ИнвНомер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Оборудование.ИнвНомер Set start)

                // *** End programmer edit section *** (Оборудование.ИнвНомер Set start)
                this.fИнвНомер = value;
                // *** Start programmer edit section *** (Оборудование.ИнвНомер Set end)

                // *** End programmer edit section *** (Оборудование.ИнвНомер Set end)
            }
        }
        
        /// <summary>
        /// Название.
        /// </summary>
        // *** Start programmer edit section *** (Оборудование.Название CustomAttributes)

        // *** End programmer edit section *** (Оборудование.Название CustomAttributes)
        [StrLen(255)]
        public virtual string Название
        {
            get
            {
                // *** Start programmer edit section *** (Оборудование.Название Get start)

                // *** End programmer edit section *** (Оборудование.Название Get start)
                string result = this.fНазвание;
                // *** Start programmer edit section *** (Оборудование.Название Get end)

                // *** End programmer edit section *** (Оборудование.Название Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Оборудование.Название Set start)

                // *** End programmer edit section *** (Оборудование.Название Set start)
                this.fНазвание = value;
                // *** Start programmer edit section *** (Оборудование.Название Set end)

                // *** End programmer edit section *** (Оборудование.Название Set end)
            }
        }
        
        /// <summary>
        /// Оборудование.
        /// </summary>
        // *** Start programmer edit section *** (Оборудование.Операции CustomAttributes)

        // *** End programmer edit section *** (Оборудование.Операции CustomAttributes)
        [PropertyStorage(new string[] {
                "Операции"})]
        [NotNull()]
        public virtual IIS.Serezhatatarincev2.Операции Операции
        {
            get
            {
                // *** Start programmer edit section *** (Оборудование.Операции Get start)

                // *** End programmer edit section *** (Оборудование.Операции Get start)
                IIS.Serezhatatarincev2.Операции result = this.fОперации;
                // *** Start programmer edit section *** (Оборудование.Операции Get end)

                // *** End programmer edit section *** (Оборудование.Операции Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Оборудование.Операции Set start)

                // *** End programmer edit section *** (Оборудование.Операции Set start)
                this.fОперации = value;
                // *** Start programmer edit section *** (Оборудование.Операции Set end)

                // *** End programmer edit section *** (Оборудование.Операции Set end)
            }
        }
        
        /// <summary>
        /// Оборудование.
        /// </summary>
        // *** Start programmer edit section *** (Оборудование.Пользователь CustomAttributes)

        // *** End programmer edit section *** (Оборудование.Пользователь CustomAttributes)
        [PropertyStorage(new string[] {
                "Пользователь"})]
        [NotNull()]
        public virtual IIS.Serezhatatarincev2.Пользователь Пользователь
        {
            get
            {
                // *** Start programmer edit section *** (Оборудование.Пользователь Get start)

                // *** End programmer edit section *** (Оборудование.Пользователь Get start)
                IIS.Serezhatatarincev2.Пользователь result = this.fПользователь;
                // *** Start programmer edit section *** (Оборудование.Пользователь Get end)

                // *** End programmer edit section *** (Оборудование.Пользователь Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Оборудование.Пользователь Set start)

                // *** End programmer edit section *** (Оборудование.Пользователь Set start)
                this.fПользователь = value;
                // *** Start programmer edit section *** (Оборудование.Пользователь Set end)

                // *** End programmer edit section *** (Оборудование.Пользователь Set end)
            }
        }
        
        /// <summary>
        /// Оборудование.
        /// </summary>
        // *** Start programmer edit section *** (Оборудование.Тип CustomAttributes)

        // *** End programmer edit section *** (Оборудование.Тип CustomAttributes)
        [PropertyStorage(new string[] {
                "Тип"})]
        [NotNull()]
        public virtual IIS.Serezhatatarincev2.Тип Тип
        {
            get
            {
                // *** Start programmer edit section *** (Оборудование.Тип Get start)

                // *** End programmer edit section *** (Оборудование.Тип Get start)
                IIS.Serezhatatarincev2.Тип result = this.fТип;
                // *** Start programmer edit section *** (Оборудование.Тип Get end)

                // *** End programmer edit section *** (Оборудование.Тип Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Оборудование.Тип Set start)

                // *** End programmer edit section *** (Оборудование.Тип Set start)
                this.fТип = value;
                // *** Start programmer edit section *** (Оборудование.Тип Set end)

                // *** End programmer edit section *** (Оборудование.Тип Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Serezhatatarincev2.РабочееМесто.
        /// </summary>
        // *** Start programmer edit section *** (Оборудование.РабочееМесто CustomAttributes)

        // *** End programmer edit section *** (Оборудование.РабочееМесто CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "РабочееМесто"})]
        public virtual IIS.Serezhatatarincev2.РабочееМесто РабочееМесто
        {
            get
            {
                // *** Start programmer edit section *** (Оборудование.РабочееМесто Get start)

                // *** End programmer edit section *** (Оборудование.РабочееМесто Get start)
                IIS.Serezhatatarincev2.РабочееМесто result = this.fРабочееМесто;
                // *** Start programmer edit section *** (Оборудование.РабочееМесто Get end)

                // *** End programmer edit section *** (Оборудование.РабочееМесто Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Оборудование.РабочееМесто Set start)

                // *** End programmer edit section *** (Оборудование.РабочееМесто Set start)
                this.fРабочееМесто = value;
                // *** Start programmer edit section *** (Оборудование.РабочееМесто Set end)

                // *** End programmer edit section *** (Оборудование.РабочееМесто Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ОборудованиеE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОборудованиеE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОборудованиеE", typeof(IIS.Serezhatatarincev2.Оборудование));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of Оборудование.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfОборудование CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfОборудование CustomAttributes)
    public class DetailArrayOfОборудование : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Serezhatatarincev2.DetailArrayOfОборудование members)

        // *** End programmer edit section *** (IIS.Serezhatatarincev2.DetailArrayOfОборудование members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type Оборудование by index.
        /// </summary>
        /// <summary>
        /// Adds object with type Оборудование.
        /// </summary>
        public DetailArrayOfОборудование(IIS.Serezhatatarincev2.РабочееМесто fРабочееМесто) : 
                base(typeof(Оборудование), ((ICSSoft.STORMNET.DataObject)(fРабочееМесто)))
        {
        }
        
        public IIS.Serezhatatarincev2.Оборудование this[int index]
        {
            get
            {
                return ((IIS.Serezhatatarincev2.Оборудование)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Serezhatatarincev2.Оборудование dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
