//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Serezhatatarincev2
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Операции.
    /// </summary>
    // *** Start programmer edit section *** (Операции CustomAttributes)

    // *** End programmer edit section *** (Операции CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ОперацииE", new string[] {
            "Дата as \'Дата\'",
            "Действие as \'Действие\'",
            "Состояние as \'Состояние\'",
            "Пользователь as \'Пользователь\'",
            "Пользователь.ФИО as \'ФИО\'"}, Hidden=new string[] {
            "Пользователь.ФИО"})]
    [MasterViewDefineAttribute("ОперацииE", "Пользователь", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИО")]
    [View("ОперацииL", new string[] {
            "Дата as \'Дата\'",
            "Действие as \'Действие\'",
            "Состояние as \'Состояние\'",
            "Пользователь.ФИО as \'ФИО\'"})]
    public class Операции : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДата;
        
        private IIS.Serezhatatarincev2.Действие fДействие;
        
        private IIS.Serezhatatarincev2.Состояние fСостояние;
        
        private IIS.Serezhatatarincev2.Пользователь fПользователь;
        
        // *** Start programmer edit section *** (Операции CustomMembers)

        // *** End programmer edit section *** (Операции CustomMembers)

        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (Операции.Дата CustomAttributes)

        // *** End programmer edit section *** (Операции.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (Операции.Дата Get start)

                // *** End programmer edit section *** (Операции.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (Операции.Дата Get end)

                // *** End programmer edit section *** (Операции.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Операции.Дата Set start)

                // *** End programmer edit section *** (Операции.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (Операции.Дата Set end)

                // *** End programmer edit section *** (Операции.Дата Set end)
            }
        }
        
        /// <summary>
        /// Действие.
        /// </summary>
        // *** Start programmer edit section *** (Операции.Действие CustomAttributes)

        // *** End programmer edit section *** (Операции.Действие CustomAttributes)
        public virtual IIS.Serezhatatarincev2.Действие Действие
        {
            get
            {
                // *** Start programmer edit section *** (Операции.Действие Get start)

                // *** End programmer edit section *** (Операции.Действие Get start)
                IIS.Serezhatatarincev2.Действие result = this.fДействие;
                // *** Start programmer edit section *** (Операции.Действие Get end)

                // *** End programmer edit section *** (Операции.Действие Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Операции.Действие Set start)

                // *** End programmer edit section *** (Операции.Действие Set start)
                this.fДействие = value;
                // *** Start programmer edit section *** (Операции.Действие Set end)

                // *** End programmer edit section *** (Операции.Действие Set end)
            }
        }
        
        /// <summary>
        /// Состояние.
        /// </summary>
        // *** Start programmer edit section *** (Операции.Состояние CustomAttributes)

        // *** End programmer edit section *** (Операции.Состояние CustomAttributes)
        public virtual IIS.Serezhatatarincev2.Состояние Состояние
        {
            get
            {
                // *** Start programmer edit section *** (Операции.Состояние Get start)

                // *** End programmer edit section *** (Операции.Состояние Get start)
                IIS.Serezhatatarincev2.Состояние result = this.fСостояние;
                // *** Start programmer edit section *** (Операции.Состояние Get end)

                // *** End programmer edit section *** (Операции.Состояние Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Операции.Состояние Set start)

                // *** End programmer edit section *** (Операции.Состояние Set start)
                this.fСостояние = value;
                // *** Start programmer edit section *** (Операции.Состояние Set end)

                // *** End programmer edit section *** (Операции.Состояние Set end)
            }
        }
        
        /// <summary>
        /// Операции.
        /// </summary>
        // *** Start programmer edit section *** (Операции.Пользователь CustomAttributes)

        // *** End programmer edit section *** (Операции.Пользователь CustomAttributes)
        [PropertyStorage(new string[] {
                "Пользователь"})]
        [NotNull()]
        public virtual IIS.Serezhatatarincev2.Пользователь Пользователь
        {
            get
            {
                // *** Start programmer edit section *** (Операции.Пользователь Get start)

                // *** End programmer edit section *** (Операции.Пользователь Get start)
                IIS.Serezhatatarincev2.Пользователь result = this.fПользователь;
                // *** Start programmer edit section *** (Операции.Пользователь Get end)

                // *** End programmer edit section *** (Операции.Пользователь Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Операции.Пользователь Set start)

                // *** End programmer edit section *** (Операции.Пользователь Set start)
                this.fПользователь = value;
                // *** Start programmer edit section *** (Операции.Пользователь Set end)

                // *** End programmer edit section *** (Операции.Пользователь Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ОперацииE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОперацииE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОперацииE", typeof(IIS.Serezhatatarincev2.Операции));
                }
            }
            
            /// <summary>
            /// "ОперацииL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОперацииL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОперацииL", typeof(IIS.Serezhatatarincev2.Операции));
                }
            }
        }
    }
}
