//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Serezhatatarincev2
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Состояние.
    /// </summary>
    // *** Start programmer edit section *** (Состояние CustomAttributes)

    // *** End programmer edit section *** (Состояние CustomAttributes)
    public enum Состояние
    {
        
        // *** Start programmer edit section *** (Состояние.Отличное CustomAttributes)

        // *** End programmer edit section *** (Состояние.Отличное CustomAttributes)
        [Caption("Отличное")]
        Отличное,
        
        // *** Start programmer edit section *** (Состояние.Хорошое CustomAttributes)

        // *** End programmer edit section *** (Состояние.Хорошое CustomAttributes)
        [Caption("Хорошое")]
        Хорошое,
        
        // *** Start programmer edit section *** (Состояние.Плохое CustomAttributes)

        // *** End programmer edit section *** (Состояние.Плохое CustomAttributes)
        [Caption("Плохое")]
        Плохое,
    }
}
