import IISSerezhatatarincev2ПользовательEController from '../i-i-s-serezhatatarincev2-пользователь-e';

var IISSerezhatatarincev2ПользовательENewController = IISSerezhatatarincev2ПользовательEController;
export default IISSerezhatatarincev2ПользовательENewController;
